[package]
name = "hello-world"
version = "0.1.0"
authors = ["Veetaha <gerzoh1@gmail.com>"]
edition = "2018"
licence ="MIT"
description = "My package description here! ;o"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
